ci update

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -30,17 +30,30 @@ jobs:
 
       # Check Docker Compose Version
       - name: Check Docker Compose Version
-        run: docker-compose --version
+        run: docker compose version
 
-      # Build and Run Docker Compose
+      # Ensure Previous Containers Are Down
+      - name: Stop All Containers
+        run: docker compose down -v || true
+
+      # Build and Start Docker Compose
       - name: Build and Start Docker Compose
-        run: docker compose -f docker-compose.yaml up --build -d
+        run: docker compose -f docker-compose.yml up --build -d
+
+      # Wait for Services to Start
+      - name: Wait for Services to Start
+        run: sleep 10
 
       # Run Tests
       - name: Run Tests
         run: |
           docker compose exec casacue_backend dotnet test /app/CasaCue.Tests/CasaCue.Tests.csproj
           docker compose exec casacue_auth dotnet test /app/CasaCue.Auth.Tests/CasaCue.Auth.Tests.csproj
+
+      # Collect Logs on Failure
+      - name: Collect Logs on Failure
+        if: failure()
+        run: docker compose logs > docker-compose-logs.txt
 
       # Stop and Clean Up Docker Compose
       - name: Clean Up
